# Generated by Django 4.1.1 on 2022-09-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsblog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NewsBlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scrapeddata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('headline', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('written_by', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ScrapedData',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='lastruntime',
            options={'managed': False},
        ),
    ]
